---
title: "Hospitalization and Death rate of Covid-19 in Texas"
author: "SIMEON ALFA"
date: "2021-03-02"
output: github_document
---

## Abstract

Coronavirus disease (COVID-19) is an infectious disease caused by the newly discovered coronavirus. The COVID-19 virus spreads primarily through droplets of saliva or discharge from the nose when an infected person coughs or sneezes. In the Us COVID-19 was declared a pandemic by the WHO in March 2020. What is the effect of rate of hospitalization due to COVID-19 in the spread of the virus? In this study we are going to evaluate this question using Texas as a case study. with the aid of exploratory data analysis, we are going to compare the hospitalization rates and then compare it to the number of deaths recorded. From the results of this data analysis, I should be able to conclude that that increased hospitalization either increases or decreases the spread of Covid in Texas

## Introduction

## Methods

### Data Acquisition

The data for this project was gathered from covid data tracking website through the Lab website for Quantitative Biology.

This website '' The COVID Tracking Project at Atlantic''(Atlantic covid tracking, 2021) contained relevant covid statistics fro all the 50 states in the country. I did not have to request access for this website, I just had to click the link, copy it into R Studio and run it with the read csv function.

### Data Description

Each row in this data represent a day in the state of Texas. Data is recorded everyday since the 3rd of March 2020.

### Data Preparation

In this project we used Rstudio (R Core Team, 2021) to clean up and prepare our data. First we loaded the tidyverse package (wickham et al, 2019)

**References**

-   R Core Team (2021). R: A language and environment for statistical computing. R Foundation for Statistical Computing, Vienna, Austria. URL <https://www.R-project.org/>.

-   Wickham et al., (2019). Welcome to the tidyverse. Journal of Open Source Software, 4(43), 1686, <https://doi.org/10.21105/joss.01686>
